### ISSUE TITLE
Ability to set content-length in the HTTP Headers

### ISSUE THREAD

**Issue by TreaHorton** [David-Barrett-MS/SOAPe#4]
I am able to add 'content-length' to the HTTP Headers Input section, but it does not appear to be honored.
I am able to set this using other tools such as cURL and it would be very helpful in certain scenarios to have this ability.
Would it be possible to allow the tool to override this header?
 
[SOAPe_Headers.docx](https://github.com/David-Barrett-MS/SOAPe/files/13441498/SOAPe_Headers.docx)

**Comment by David-Barrett-MS** [comment]
I've implemented this in v1.2.5 (which will be published shortly), though all it will do is generate an error if the content-length is incorrect (as the HttpWebRequest class used by SOAPe will return an error).
